config/routes.rb
Rails.application.routes.draw do
  resources :songs
  resources :users, only: [:new, :create, :show]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  namespace :admin do
    resources :categories
  end
end

app/models/song.rb
class Song < ActiveRecord::Base
  validates_presence_of :title, :artist

  validates :title, presence: true
  validates :artist, presence: true
  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :songs

  validates :username, presence: true,
                      uniqueness: true

  enum role: %w(default admin)

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController

  before_action :require_admin

  def require_admin
    render file: "/public/404" unless current_admin?
  end

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    #raise params.inspect
    @user = User.find_by_username(params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash.now[:error] = "Invalid Login"
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to login_path
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update]
  helper_method :most_recent_song

  def index
    @songs = Song.all
    # most_recent_song
    # @songs = Song.where(title: @search_term)
  end

  # def most_recent_song
  #   session[:most_recent_song_id] = Song.last.id
  # end

  def show
    @song = Song.find(params[:id])
  end

  def new
    @song = Song.new
  end

  def create
    # Song.create(song_params)
    # redirect_to songs_path

    @song = Song.new(song_params)
    if @song.save  #it looking for a truthy value
      flash[:notice] = "Song successfully saved."
      redirect_to songs_path
    else
      flash.now[:errors] = "Do it right!"
      render :new
    end
  end

  def edit
  end

  def update
    if @song.update(song_params)
      redirect_to @song
    else
      flash.now[:errors] = @song.errors.full_messages.join(", ")
      render :edit
    end
  end

  def destroy
    # song = Song.find(params[:id])
    # song.destroy

    Song.destroy(params[:id])
    redirect_to songs_path
  end

  private

  def set_song
    @song = Song.find(params[:id])
  end

  def song_params
    params.require(:song).permit(:title, :artist)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user=User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash.now[:errors] = @user.errors.full_messages.join(", ")
      render :new
    end

    def show
      @user = current_user
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/index.html.erb
<h1>All Categories</h1>

app/views/layouts/application.html.erb
<!-- layout gets renered everywhere -->
<!DOCTYPE html>
<html>
<head>
  <title>MyJams</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if current_user %>
    <%= link_to "Logout", logout_path, method: :delete%><% end %>
    <%= flash.each do |name, msg| %>
    <%content_tag :div, msg, id: "flash_#{name}"%>
    <% end %>
<%= yield %>

</body>
</html>

app/views/songs/_form.html.erb
<%= flash.now[:errors] %>

<%= form_for(@song) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %> <br>
  <%= f.label :artist %>
  <%= f.text_field :artist %> <br>
  <%= f.submit %>
<% end %>

app/views/songs/edit.html.erb
<h1>Edit a Song</h1>

<%= render partial: 'form' %>

app/views/songs/index.html.erb
<h1>All Songs</h1>

<% @songs.each do |song| %>
  <li>
    <%= link_to(song.title, song) %>
    <%= link_to "Edit", edit_song_path(song) %>
    <%= link_to "Delete", song_path(song), method: :delete %>
  </li>
<% end %>

<%= link_to "New Song", new_song_path %>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render partial: 'form' %>

<%= flash.each do |type, message| %>
<%= content_tag :div, message, class: "flash_#{type}"%>

<% end %>

app/views/songs/show.html.erb
<h1><%= @song.title %></h1>
<p><%= @song.artist %></p>

app/views/users/new.html.erb
<h1>Create New Account</h1>

<%= form_for(@user) do |f|%>
<%= f.label :username %>
<%= f.text_field :username %> <br>
<%= f.label :password %>
<%= f.text_field :password %> <br>
<%= f.submit "Create Account" %>
<% end %>

app/views/users/show.html.erb
<h1><%="#{current_user.username}'s Jams"%></h1>
Welcome, <%= current_user.username %> <br>

<% current_user.songs.each do |song| %>
<%= song.title %>
<% end %>